# Hyperparameter tuning parameters

# configs/sweep_config.yaml
program: train_classifier.py
method: bayes # Bayesian optimization finds the global minimum faster than random search
metric:
  name: val_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-2
  batch_size:
    values: [128, 256, 512]
  classifier.lstm.hidden_dim:
    values: [32, 64, 128]
  classifier.lstm.num_layers:
    values: [1, 2, 3]
  classifier.cnn1d.dropout:
    distribution: uniform
    min: 0.1
    max: 0.5